version: 2

sources:
    - name: staging
      #For bigquery:
      database: healthy-fuze-339218

      schema: trips_data_all

      # loaded_at_field: record_loaded_at
      tables:
        - name: green_tripdata
        - name: yellow_tripdata
        - name: external_fhv_tripdata
         # freshness:
           # error_after: {count: 6, period: hour}

